#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=32000m 
#SBATCH --time=10:00
#SBATCH --account=eecs498f21_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1

if [ "$#" -ne 1 ]; then
    echo "Usage: sbatch run_test [32-character hash]"
    exit 1
fi

time ./md5 $1